import {
  Cog,
  Building2,
  Rocket,
  Users,
  Palette,
  Globe,
  Code,
  Megaphone,
  Database,
  Bot,
} from 'lucide-react'

export const WHATSAPP_LINK = "https://chat.whatsapp.com/JjXY8iuVwnQKkgDnivs6A0"
export const CALENDLY_LINK = "https://calendly.com/info-vsualdm/30min"

export const services = [
  {
    id: "business-automation",
    icon: Cog,
    title: "Business Automation",
    description: "Streamline operations with intelligent automation systems that save time and reduce errors",
    longDescription: "Transform your business operations with our cutting-edge automation solutions. We analyze your workflows, identify bottlenecks, and implement intelligent systems that work 24/7, reducing manual tasks by up to 80%.",
    color: "from-rose-500 to-pink-600",
    features: [
      "Workflow Automation",
      "Process Optimization",
      "Integration Solutions",
      "Task Scheduling",
      "Error Reduction",
      "Cost Savings",
    ],
    benefits: ["Save 20+ hours weekly", "Reduce errors by 90%", "Scale operations effortlessly"],
  },
  {
    id: "business-system-build",
    icon: Building2,
    title: "Business System Build & Automation",
    description: "Complete infrastructure development with automated systems for scalable growth",
    longDescription: "Build a solid foundation for your business with comprehensive system architecture. We design and implement complete business infrastructure that scales with your growth.",
    color: "from-violet-500 to-purple-600",
    features: [
      "System Architecture",
      "Custom Development",
      "Automation Setup",
      "Database Design",
      "API Integration",
      "Cloud Infrastructure",
    ],
    benefits: ["Future-proof architecture", "Seamless integrations", "Enterprise-grade security"],
  },
  {
    id: "growth-engine",
    icon: Rocket,
    title: "Growth Engine",
    description: "Revenue acceleration systems designed to supercharge your business growth",
    longDescription: "Accelerate your revenue with data-driven growth strategies. Our Growth Engine combines marketing automation, sales optimization, and customer retention systems.",
    color: "from-amber-500 to-orange-600",
    features: [
      "Revenue Optimization",
      "Market Expansion",
      "Growth Strategies",
      "Sales Automation",
      "Customer Retention",
      "Analytics Dashboard",
    ],
    benefits: ["5x average ROI", "Predictable revenue", "Sustainable growth"],
  },
  {
    id: "lead-growth-engine",
    icon: Users,
    title: "Lead Growth Engine",
    description: "Predictable lead generation systems that keep your pipeline flowing",
    longDescription: "Never run out of qualified leads again. Our Lead Growth Engine creates a consistent flow of prospects through multi-channel marketing and intelligent nurturing sequences.",
    color: "from-emerald-500 to-teal-600",
    features: [
      "Lead Generation",
      "Funnel Optimization",
      "Conversion Tracking",
      "Email Sequences",
      "Landing Pages",
      "A/B Testing",
    ],
    benefits: ["300% more leads", "Higher conversion rates", "Lower acquisition cost"],
  },
  {
    id: "brand-content-creation",
    icon: Palette,
    title: "Brand Content Creation",
    description: "Compelling content that tells your story and connects with your audience",
    longDescription: "Stand out with premium brand content that resonates. From visual design to compelling copy, we create content that builds trust and drives action.",
    color: "from-pink-500 to-rose-600",
    features: [
      "Visual Design",
      "Copywriting",
      "Brand Strategy",
      "Social Media Content",
      "Video Production",
      "Brand Guidelines",
    ],
    benefits: ["Consistent brand voice", "Higher engagement", "Professional presence"],
  },
  {
    id: "website-development",
    icon: Globe,
    title: "Website Development",
    description: "High-performance websites that convert visitors into customers",
    longDescription: "Your website is your digital storefront. We build stunning, fast-loading websites optimized for conversions and search engines.",
    color: "from-cyan-500 to-blue-600",
    features: [
      "Custom Design",
      "Responsive Development",
      "SEO Optimization",
      "Performance Tuning",
      "CMS Integration",
      "E-commerce Solutions",
    ],
    benefits: ["2x faster load times", "Mobile-first design", "SEO-optimized"],
  },
  {
    id: "software-development",
    icon: Code,
    title: "Software Development",
    description: "Custom solutions tailored to your unique business requirements",
    longDescription: "Get software that fits your business perfectly. We develop custom applications, APIs, and integrations that solve your specific challenges.",
    color: "from-indigo-500 to-violet-600",
    features: [
      "Custom Apps",
      "API Development",
      "System Integration",
      "Mobile Development",
      "SaaS Solutions",
      "Maintenance & Support",
    ],
    benefits: ["Tailored solutions", "Scalable architecture", "Ongoing support"],
  },
  {
    id: "paid-ads",
    icon: Megaphone,
    title: "Paid Ads",
    description: "Strategic advertising across all social media platforms for maximum ROI",
    longDescription: "Maximize your ad spend with data-driven campaigns. We manage advertising across Facebook, Google, TikTok, LinkedIn, and more to deliver qualified leads.",
    color: "from-red-500 to-rose-600",
    features: [
      "Facebook Ads",
      "Google Ads",
      "TikTok Ads",
      "LinkedIn Ads",
      "Retargeting",
      "Campaign Optimization",
    ],
    benefits: ["Lower CPA", "Higher ROAS", "Qualified traffic"],
  },
  {
    id: "go-high-level-crm",
    icon: Database,
    title: "Go High Level CRM",
    description: "Lead growth and management with the most powerful CRM solution",
    longDescription: "Harness the power of Go High Level CRM for complete lead management. We set up and optimize your CRM for maximum efficiency and conversion.",
    color: "from-green-500 to-emerald-600",
    features: [
      "Lead Management",
      "Pipeline Tracking",
      "Automated Follow-ups",
      "SMS Marketing",
      "Appointment Booking",
      "Reporting Dashboard",
    ],
    benefits: ["Never lose a lead", "Automated nurturing", "Complete visibility"],
  },
  {
    id: "ai-powered-automation",
    icon: Bot,
    title: "AI-Powered Automation",
    description: "Intelligent automation that learns and adapts to your business needs",
    longDescription: "Leverage the power of artificial intelligence to automate complex tasks. Our AI solutions learn from your data to deliver increasingly better results.",
    color: "from-purple-500 to-pink-600",
    features: [
      "AI Chatbots",
      "Predictive Analytics",
      "Smart Workflows",
      "Natural Language Processing",
      "Machine Learning",
      "Intelligent Routing",
    ],
    benefits: ["24/7 intelligent support", "Predictive insights", "Continuous improvement"],
  },
]

export const processSteps = [
  { step: 1, title: "Discovery", description: "We analyze your business needs and goals", icon: "🔍" },
  { step: 2, title: "Strategy", description: "Custom plan tailored to your objectives", icon: "📋" },
  { step: 3, title: "Development", description: "Building your solution with precision", icon: "⚡" },
  { step: 4, title: "Launch", description: "Deploying and optimizing for success", icon: "🚀" },
]

export const testimonials = [
  {
    name: "Sarah Johnson",
    role: "CEO, TechStart Inc.",
    content: "VSUAL transformed our entire digital presence. The automation systems they built saved us 20+ hours per week.",
    rating: 5,
  },
  {
    name: "Michael Chen",
    role: "Founder, GrowthPro",
    content: "The lead generation engine they built increased our conversions by 300%. Absolutely phenomenal results!",
    rating: 5,
  },
  {
    name: "Emily Rodriguez",
    role: "Marketing Director",
    content: "Their AI-powered solutions have revolutionized how we handle customer interactions. Game changer!",
    rating: 5,
  },
]

export const stats = [
  { value: "150+", label: "Projects Delivered" },
  { value: "98%", label: "Client Satisfaction" },
  { value: "5x", label: "Average ROI" },
  { value: "24/7", label: "Support" },
]
